project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true

  # (other formats)
  typst:
    bibliographystyle: ieee
    
execute:
  freeze: false



